registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: certs/docker-reg.uae.crt
    REGISTRY_HTTP_TLS_KEY: certs/docker-reg.uae.key
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
  volumes:
    - ~/myRegistry:/var/lib/registry
    - ~/registry/certs:/certs
