registry:
  restart: always
  image: registry:2
  ports:
    - 5000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: certs/secure.example.com.crt
    REGISTRY_HTTP_TLS_KEY: certs/secure.example.com.key
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
  volumes:
    - ~/myRegistry:/var/lib/registry
    - $PWD/certs:/certs
